name: datalab
channels:
  - conda-forge
  - nodefaults
dependencies:
  - sqlite
  - requests
  - pandas
  - jinja2
  - xarray
  - netcdf4
  - dask
  - matplotlib
  - cartopy
  - zarr
  - s3fs
  - seaborn
  - basemap
  - ipykernel
  - 'libnetcdf<4.9'
  - r-base
  - r-ggplot2
  - r-loader
  - r-transformer
  - r-visualizer
  - r-irkernel
  - r-geoprocessor
  - r-downscaler
  - r-convertr
  - r-devtools
  - r-climate4r.climdex
  - r-drought4r
  - r-loader.2nc
